-- MySQL Script generated by MySQL Workbench
-- Fri Dec 13 20:17:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Secretaria_Administrativa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Secretaria_Administrativa` ;

-- -----------------------------------------------------
-- Schema Secretaria_Administrativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Secretaria_Administrativa` DEFAULT CHARACTER SET utf8 ;
USE `Secretaria_Administrativa` ;

-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Docentes` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Docentes` (
  `idDocentes` INT NOT NULL AUTO_INCREMENT,
  `Doc_nombre` VARCHAR(45) NOT NULL,
  `doc_segundo_nombre` VARCHAR(45) NULL,
  `Doc_Apellido` VARCHAR(45) NOT NULL,
  `doc_segundo_apellido` VARCHAR(45) NULL,
  `Doc_Cedula` INT NULL,
  `Doc_Fecha_de_nacimiento` DATE NULL,
  `doc_genero` VARCHAR(15) NOT NULL,
  `Doc_tipoSangre` VARCHAR(3) NULL,
  `Doc_estadoCivil` VARCHAR(15) NULL,
  `doc_peso` DOUBLE NULL,
  `doc_estatura` DOUBLE NULL,
  `Doc_Provincia` VARCHAR(45) NULL,
  `doc_distrito` VARCHAR(20) NULL,
  `Doc_Corregimiento` VARCHAR(45) NULL,
  `Doc_Direccion` VARCHAR(45) NULL,
  `Doc_Telefono` INT NULL,
  `Doc_Correo` VARCHAR(45) NOT NULL,
  `Doc_Sede` VARCHAR(45) NOT NULL,
  `Doc_Categoria` VARCHAR(45) NULL,
  `Doc_Departamento` VARCHAR(45) NULL,
  `Extensión` VARCHAR(45) NULL,
  `Apatado_postal` VARCHAR(45) NULL,
  `Docentescol` VARCHAR(45) NULL,
  `cargo_administrativo` VARCHAR(45) NULL,
  `Representante_gobierno` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Administrativos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Administrativos` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Administrativos` (
  `idSecretarias` INT NOT NULL AUTO_INCREMENT,
  `Sec_Nombre` VARCHAR(45) NOT NULL,
  `Segundo_nombre` VARCHAR(45) NULL,
  `Sec_Apellido` VARCHAR(45) NOT NULL,
  `Segundo_apellido` VARCHAR(45) NULL,
  `Sec_Cedula` INT NULL,
  `Sec_Fecha_de_Nacimiento` DATE NULL,
  `genero` VARCHAR(45) NOT NULL,
  `cargo_administrativo` VARCHAR(45) NOT NULL,
  `admi_estado_civil` VARCHAR(10) NULL,
  `admi_tipoSangre` VARCHAR(3) NULL,
  `admi_peso` DOUBLE NULL,
  `admi_estatura` DOUBLE NULL,
  `Sec_Provincia` VARCHAR(45) NULL,
  `admi_distrito` VARCHAR(20) NULL,
  `Sec_Corregimiento` VARCHAR(45) NULL,
  `Sec_Direccion` VARCHAR(45) NULL,
  `Sec_Telefono` INT NOT NULL,
  `Sec_correo` VARCHAR(45) NOT NULL,
  `Sec_Unidad` VARCHAR(45) NULL,
  `sec_sede` VARCHAR(45) NOT NULL,
  `sec_representante_gobierno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSecretarias`),
  UNIQUE INDEX `Sec_Cedula_UNIQUE` (`Sec_Cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Preparacion_Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Preparacion_Docente` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Preparacion_Docente` (
  `idPreparacion_Docente` INT NOT NULL AUTO_INCREMENT,
  `Tit_Nombre` VARCHAR(45) NOT NULL,
  `Tit_Año` INT NOT NULL,
  `Tit_Universidad` VARCHAR(45) NULL,
  `Tit_Grado` VARCHAR(45) NULL COMMENT 'Licenciatura\nDoctorado\nPosgrado\nDiplomado',
  `Docentes_idDocentes` INT NOT NULL,
  PRIMARY KEY (`idPreparacion_Docente`, `Docentes_idDocentes`),
  INDEX `fk_Preparacion_Docente_Docentes1_idx` (`Docentes_idDocentes` ASC) VISIBLE,
  CONSTRAINT `fk_Preparacion_Docente_Docentes1`
    FOREIGN KEY (`Docentes_idDocentes`)
    REFERENCES `Secretaria_Administrativa`.`Docentes` (`idDocentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Capacitacion_Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Capacitacion_Docente` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Capacitacion_Docente` (
  `idCapacitacion_Docente` INT NOT NULL AUTO_INCREMENT,
  `Cap_Nombre` VARCHAR(45) NOT NULL,
  `Cap_Año` INT NOT NULL,
  `Cap_Rol` VARCHAR(45) NULL,
  `Cap_Horas` INT NULL,
  `Cap_Istitucion` VARCHAR(45) NULL,
  `Docentes_idDocentes` INT NOT NULL,
  PRIMARY KEY (`idCapacitacion_Docente`, `Docentes_idDocentes`),
  INDEX `fk_Capacitacion_Docente_Docentes1_idx` (`Docentes_idDocentes` ASC) VISIBLE,
  CONSTRAINT `fk_Capacitacion_Docente_Docentes1`
    FOREIGN KEY (`Docentes_idDocentes`)
    REFERENCES `Secretaria_Administrativa`.`Docentes` (`idDocentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Preparacion_Administrativos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Preparacion_Administrativos` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Preparacion_Administrativos` (
  `idPreparacion_Administrativos` INT NOT NULL AUTO_INCREMENT,
  `Tit_Nombre` VARCHAR(45) NULL,
  `Tit_Año` INT NULL,
  `Tit_Universidad` VARCHAR(45) NULL,
  `Tit_Grado` VARCHAR(45) NULL COMMENT 'Licenciatura\nDoctorado\nPosgrado\nDiplomado',
  `Administrativos_idSecretarias` INT NOT NULL,
  PRIMARY KEY (`idPreparacion_Administrativos`, `Administrativos_idSecretarias`),
  INDEX `fk_Preparacion_Administrativos_Administrativos1_idx` (`Administrativos_idSecretarias` ASC) VISIBLE,
  CONSTRAINT `fk_Preparacion_Administrativos_Administrativos1`
    FOREIGN KEY (`Administrativos_idSecretarias`)
    REFERENCES `Secretaria_Administrativa`.`Administrativos` (`idSecretarias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Material_de_Oficina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Material_de_Oficina` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Material_de_Oficina` (
  `idMaterial_de_Oficina` INT NOT NULL AUTO_INCREMENT,
  `Mat_Nombre` VARCHAR(45) NOT NULL,
  `Mat_Cantidad` INT NOT NULL,
  PRIMARY KEY (`idMaterial_de_Oficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Usuarios` (
  `id_user` INT NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cedula` VARCHAR(15) NOT NULL,
  `Rol` VARCHAR(45) NULL,
  `Docentes_idDocentes` INT NOT NULL,
  `Administrativos_idSecretarias` INT NOT NULL,
  PRIMARY KEY (`id_user`, `Docentes_idDocentes`, `Administrativos_idSecretarias`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `fk_Usuarios_Docentes1_idx` (`Docentes_idDocentes` ASC) VISIBLE,
  INDEX `fk_Usuarios_Administrativos1_idx` (`Administrativos_idSecretarias` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Docentes1`
    FOREIGN KEY (`Docentes_idDocentes`)
    REFERENCES `Secretaria_Administrativa`.`Docentes` (`idDocentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Administrativos1`
    FOREIGN KEY (`Administrativos_idSecretarias`)
    REFERENCES `Secretaria_Administrativa`.`Administrativos` (`idSecretarias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Familia_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Familia_doc` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Familia_doc` (
  `idFamilia_doc` INT NOT NULL,
  `nombre_fam` VARCHAR(20) NOT NULL,
  `apellido_fam` VARCHAR(20) NOT NULL,
  `Localizar_emergencia` VARCHAR(5) NOT NULL,
  `Prioridad_localizar` INT NOT NULL,
  `Parentesco` VARCHAR(10) NOT NULL,
  `Fecha_nacimiento` DATE NULL,
  `Celular` VARCHAR(20) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `Docentes_idDocentes` INT NOT NULL,
  PRIMARY KEY (`idFamilia_doc`, `Docentes_idDocentes`),
  INDEX `fk_Familia_doc_Docentes1_idx` (`Docentes_idDocentes` ASC) VISIBLE,
  CONSTRAINT `fk_Familia_doc_Docentes1`
    FOREIGN KEY (`Docentes_idDocentes`)
    REFERENCES `Secretaria_Administrativa`.`Docentes` (`idDocentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Familia_admi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Familia_admi` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Familia_admi` (
  `idFamilia_doc` INT NOT NULL,
  `nombre_fam` VARCHAR(20) NOT NULL,
  `apellido_fam` VARCHAR(20) NOT NULL,
  `Localizar_emergencia` VARCHAR(5) NOT NULL,
  `Prioridad_localizar` INT NOT NULL,
  `Parentesco` VARCHAR(10) NOT NULL,
  `Fecha_nacimiento` DATE NULL,
  `Celular` VARCHAR(20) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `Administrativos_idSecretarias` INT NOT NULL,
  PRIMARY KEY (`idFamilia_doc`, `Administrativos_idSecretarias`),
  INDEX `fk_Familia_admi_Administrativos1_idx` (`Administrativos_idSecretarias` ASC) VISIBLE,
  CONSTRAINT `fk_Familia_admi_Administrativos1`
    FOREIGN KEY (`Administrativos_idSecretarias`)
    REFERENCES `Secretaria_Administrativa`.`Administrativos` (`idSecretarias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`Fotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Secretaria_Administrativa`.`Fotos` ;

CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`Fotos` (
  `idFotos` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descricpion` VARCHAR(45) NULL,
  `Foto` BLOB NOT NULL,
  `Docentes_idDocentes` INT NOT NULL,
  `Administrativos_idSecretarias` INT NOT NULL,
  PRIMARY KEY (`idFotos`, `Docentes_idDocentes`, `Administrativos_idSecretarias`),
  UNIQUE INDEX `idFotos_UNIQUE` (`idFotos` ASC) VISIBLE,
  INDEX `fk_Fotos_Docentes1_idx` (`Docentes_idDocentes` ASC) VISIBLE,
  INDEX `fk_Fotos_Administrativos1_idx` (`Administrativos_idSecretarias` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos_Docentes1`
    FOREIGN KEY (`Docentes_idDocentes`)
    REFERENCES `Secretaria_Administrativa`.`Docentes` (`idDocentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fotos_Administrativos1`
    FOREIGN KEY (`Administrativos_idSecretarias`)
    REFERENCES `Secretaria_Administrativa`.`Administrativos` (`idSecretarias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
