<!-- PHP necesario para que realizar el ingreso a la pagina, en este caso solicita que la persona que use la aplicacion ponga su nombre de usuario y clave para que pueda acceder-->
<?php 
    if(isset($_POST['submit'])){
    $nombre= $_POST['nombre'];
    $pass= $_POST['password'];

    echo $nombre;
    echo $password;
    }

?>
<!DOCTYPE html>
<html lang="es">
    <head>
        <!--La "cabeza" de la pagina, es su titulo, el php incluido es para que incluya detalles del boostrap  -->
        <meta charset="UTF-8" />
        <title>Iniciar Sesión</title>
        <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
    </head>
    <body>
        <!--Para un mejor control, creamos el cuerpo a base de contenedores, que a su vez se dividen en otras secciones (row y column), tambien aparece navbar y tiene la misma funcion que la antes mencionada-->
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-3" align="center">
                    <img src="http://www.utp.ac.pa/documentos/2015/imagen/logo_utp_1_300.jpg" style="width:150px;height:150px">
                </div>

                <div class="col-6" align="center">
                    <fieldset>
                    <legend><h2 style="text-align:center;color: #709e07">Universidad Tecnológica de Panamá</h2></legend>
                    <legend><h2 style="text-align:center; color: #709e07">Control de perfil de la FISC</h2></legend><br>
                    <legend><h2 style="text-align:center;color: #709e07">Inicio de Sesión</h2></legend>
                    </fieldset>
                </div>

                <div class="col-3" align="center">
                    <img src="https://pbs.twimg.com/profile_images/1099046790463193093/nb9L_nav_400x400.png" style="width:150px height:150px;" align="right">
                </div>
            </div>

        
            <div class="row justify-content-center">
                <div class="col-4" align="center">
                    <form action="http://localhost:8000/usuarios/auth"  method="post">
                        <label>Número de Cédula</label>
                        <input type="text" name="nombre" placeholder="Ej. #-###-###" class="form-control" required="true">
                                        <br><br>
                        <label>Contraseña:</label>
                        <input type="password" name="pass" placeholder="Ingrese su Contraseña" class="form-control" required="true">
                                        <br>
                        <input type="submit" value="Validar" name="submit" class="btn btn-success" required="true">
                    </form> 

                </div>
            </div>
        </div>
    </body>
</html>

