<?php 
    if(isset($_POST['submit'])){
    $nombre= $_POST['nombre'];
    $pass= $_POST['password'];

    echo $nombre;
    echo $password;
    }

?>
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Ingenieria Web</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="custom.css">
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Gestión de Perfiles</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <input align="right" type="submit" value="Cerrar Sesión" name="submit" class="btn btn-danger">
    </div>
  </nav>


  <div class="container">

    <header class="jumbotron my-4">
      <h1 class="display-3" align="center">Bienvenido al Sistema de Gestión de Perfiles</h1>
    </header>

    <div class="row justify-content-md-center">

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="https://image.flaticon.com/icons/png/512/65/65882.png" alt="">
            <a href="#" class="btn btn-success">Docentes</a>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img width= "50px" height= "253px" class="card-img-top" src="https://www.clipartwiki.com/clipimg/detail/246-2467223_admin-png-transparent-background-admin-icon.png" alt="">
            <a href="#" class="btn btn-success">Administrativo</a>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="https://simpleicon.com/wp-content/uploads/users.png" alt="">
            <a href="#" class="btn btn-success">Usuarios</a>
        </div>
      </div>

    </div>

  </div>
 
  <footer class="py-5 bg-success">  
    <div class="container">
      <br>
      <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
    </div>

  </footer>

</body>

</html>