<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Ingenieria Web</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="custom.css">
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Gestión de Perfiles</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>


  <div class="container">

    <header class="jumbotron my-4">
      <h1 class="display-3" align="center">Bienvenido al Sistema de Gestión de Perfiles</h1>
    </header>

    <div class="row justify-content-md-center">

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwj2_L7w4bbmAhXOjVkKHVCbAMIQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.flaticon.es%2Ficono-gratis%2Fprofesor-en-el-pizarron_65882&psig=AOvVaw1_294Gmo6awjd9Rx38Eo1R&ust=1576468746590099" alt="">
            <a href="#" class="btn btn-success">Docentes</a>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwi5w92k4rbmAhWvzlkKHcipDAsQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.cleanpng.com%2Ffree%2Fsystem-administrator.html&psig=AOvVaw3TpmzRUZCivfoOzKGa30gL&ust=1576468841133495" alt="">
            <a href="#" class="btn btn-success">Administrativo</a>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjT_s7O4bbmAhXptlkKHQilDR0QjRx6BAgBEAQ&url=https%3A%2F%2Fwww.pngocean.com%2Fgratis-png-clipart-bxilw&psig=AOvVaw3MfLFu6YdAIe6nj1jLXUW5&ust=1576468659219323" alt="">
            <a href="#" class="btn btn-success">Usuarios</a>
        </div>
      </div>

    </div>

  </div>
 
  <footer class="py-5 bg-success">  
    <div class="container">
      <br>
      <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
    </div>

  </footer>

</body>

</html>
