<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Usuarios</title>
        <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
    </head>
    <body>
        <?php include '/var/www/app/views/layouts/nav.php'; ?>
        <?php
            foreach ($data['users'] as $user) {
                echo $user["name"]."<br/>";
            }
        ?>
    </body>
</html>
