<!DOCTYPE html>
<html lang="es">
    <head>
        <!--La "cabeza" de la pagina, es su titulo, el php incluido es para que incluya detalles del boostrap  -->
        <meta charset="UTF-8" />
        <title>Usuarios</title>
        <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>

        <!--Estos links y scripts permiten que la apariencia de la cabeza de la pagina, sea mas adecuada -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="custom.css">
        <script src="https://kit.fontawesome.com/d1fbf856e0.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <!--El navbar, es como el menu principal que sale en todas las paginas, entonces se usa para que se pueda navegar en la aplicacion mas facilmente, se le conecta con el localhost -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top mb-5">
            <a class="navbar-brand" href="http://localhost:8000/"><i class="fas fa-arrow-left fa-2x"></i></a>

            <!--Para un mejor control, creamos el cuerpo a base de contenedores, que a su vez se dividen en otras secciones (row y column), tambien aparece navbar y tiene la misma funcion que la antes mencionada-->
            <div class="container">
                <a class="navbar-brand" href="http://localhost:8000/">Gestión de Perfiles</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        <br><br><br><br>
        <div class="container pt-5" align="center">
            
            <div class="row justify-content-center d-flex">
                <div class="col-10 justify-content-end d-flex pb-5 " align="right">
                    <button type="button" class="btn btn-success">Crear Usuario <i class="fas fa-plus"></i></button>
                </div>
                <br>
                <div class="col-10 ">
                    <div class="card table-sm">
                        <div class="card-header">
                            <h5 class="card-tittle my-2">Usuarios</h5>
                        </div>
                        <!--Por razones de comodidad, mostramos los datos en forma de tablas -->
                        <table class="table table-striped">
                            <thead>
                            </thead>
                            <tbody>

                                    <?php
                                        foreach ($data['users'] as $user) {
                                            echo "<tr>";
                                            echo "<td>".$user["name"];
                                            echo "<td>".$user["cedula"];
                                            if ($user["docentes_id"] == 0){
                                                echo "<td>"."";
                                            }else{
                                                echo "<td>"."<a href='http://localhost:8000/docentes/show/".$user["docentes_id"]."' class='btn btn-primary justify-content-center d-flex' role='button' aria-pressed='true'>Perfil Docente</a>";
                                            }
                                            if($user["administrativos_id"] == 0){
                                                echo "<td>"."";
                                            }else{
                                                echo "<td>"."<a href='http://localhost:8000/administrativos/show/".$user["administrativos_id"]."' class='btn btn-primary justify-content-center d-flex' role='button' aria-pressed='true'>Perfil Administrativo</a>";
                                            }
                                            echo "<td>"."<a href='http://localhost:8000/usuarios/show/".$user["id"]."' class='justify-content-center d-flex' role='button' aria-pressed='true'><i class='fas fa-eye fa-2x'></i></a>";
                                            //echo "<td>"."<a href='#' class='btn btn-danger justify-content-center d-flex' role='button' aria-pressed='true'>borrar</a>"; //no creemos que estos datos se deban borrar pero por si acaso lo dejaremos aqui
                                        }
                                    ?>


                            </tbody>
                        </table> 
                    </div>

                </div>
            </div>
        </div>
        <footer class="py-4 bg-success footer fixed-bottom">  
            <div class="container-fluid">
                <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
            </div>
            <!-- /.container -->
        </footer>
    </body>
</html>