   </head>
    <body>
        <?php include '/var/www/app/views/layouts/nav.php'; ?>
        <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
        <div class="row justify-content-md-center">  
                <div class="col-lg-3 col-md-6 mb-4 p-5">
                    <div class="row justify-content-md-center" align="center">
                        <div class="my-auto">
                            <img src="https://ayudawp.com/wp-content/uploads/2014/02/usuario-registrado.jpg"style="width:80px;height:80px"align="left">
                        </div>
                        <div class="my-auto">
                            <h4>Usuario</h4> 
                        </div>
                    </div>
                    <br>
                    <div class="row justify-content-md-center" align="center">
                        <form method="get" action="">
                            <input type="search" name="" placeholder="Buscar Usuario">
                            <input type="submit" value="Buscar" name="" class="btn btn-success"> 
                        </form>
                    </div>
                </div>
        </div>

        <div class="container" align="right">
            <button type="button" class="btn btn-success">Crear Usuario</button>
        </div><br>

        <div class="container p-3" align="center">
            <div class="row justify-content-center d-flex">
                <div class="col-10 border border-success">
                    <table class="table ">
                        <thead>
                        </thead>
                        <tbody>

                                <?php
                                    foreach ($data['users'] as $user) {
                                        echo "<tr>";
                                        echo "<td>".$user["name"];
                                        echo "<td>".$user["cedula"];
                                        if ($user["docentes_id"] == 0){
                                            echo "<td>"."";
                                        }else{
                                            echo "<td>"."<a href='http://localhost:8000/docentes/show/".$user["docentes_id"]."' class='btn btn-primary justify-content-center d-flex' role='button' aria-pressed='true'>Perfil Docente</a>";
                                        }
                                        if($user["administrativos_id"] == 0){
                                            echo "<td>"."";
                                        }else{
                                            echo "<td>"."<a href='http://localhost:8000/administrativos/show/".$user["administrativos_id"]."' class='btn btn-primary justify-content-center d-flex' role='button' aria-pressed='true'>Perfil Administrativo</a>";
                                        }
                                        echo "<td>"."<a href='http://localhost:8000/usuarios/show/".$user["id"]."' class='btn btn-primary justify-content-center d-flex' role='button' aria-pressed='true'>ver</a>";
                                        //echo "<td>"."<a href='#' class='btn btn-danger justify-content-center d-flex' role='button' aria-pressed='true'>borrar</a>"; //no creemos que estos datos se deban borrar pero por si acaso lo dejaremos aqui
                                    }
                                ?>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <footer class="py-4 bg-success footer fixed-bottom">  
            <div class="container-fluid">
                <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
            </div>
            <!-- /.container -->
        </footer>
    </body>
</html>