<?php 
    if(isset($_POST['submit'])){
    $nombre= $_POST['nombre'];
    $pass= $_POST['password'];

    echo $nombre;
    echo $password;
    }

?>
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Usuarios</title>
        <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
    </head>
    <body>
        <div class="container">
            <form action="http://localhost:8000/usuarios/auth"  method="post">
                <label>nombre:</label>
                <input type="text" name="nombre" class="form-control">

                <label>nombre:</label>
                <input type="password" name="pass" class="form-control">

                <input type="submit" name="submit" class="btn btn-success">
            </form>        
        </div>

    </body>
</html>

