<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <title>Usuarios</title>
    <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="custom.css">
    <script src="https://kit.fontawesome.com/d1fbf856e0.js" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
        <div class="container">
            <a class="navbar-brand" href="http://localhost:8000/">Gestión de Perfiles</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>


    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">

            <h1 class="display-3" align="center">Perfil de Usuario</h1>

        </header>

        <div class="row">
            <div class="col-12 justify-content-center d-flex">
                    <i class="fas fa-user fa-10x border m-4 p-4"></i>
                    
            </div>
            <div class="col-6">
                <div class="card table-sm">
                    <div class="card-header">
                        <h5 class="card-tittle my-2">Informacion General</h5>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <td>Nombre completo</td>
                                    <td><?php echo $data["users"]["name"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Cedula</td>
                                    <td><?php echo $data["users"]["cedula"]; ?></td>
                                </tr>
                            </tbody>
                            
                        </table>
                    </div>
                    
                </div>
            </div>
            <div class="col-6">
                <div class="col-12">
                    <div class="card table-sm">
                        <div class="card-header">
                            <h5 class="card-tittle my-2">Perfiles</h5>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tbody>
                                    <tr>
                                        <td>Nombre completo</td>
                                        <td><?php echo ($data["users"]["docentes_id"]) ? "<a href='http://localhost:8000/docentes/show/".$data["users"]["docentes_id"]."'>Ver perfil docente</a>" : "No tiene perfil Docente";?></td>
                                    </tr>
                                    <tr>
                                        <td>Cedula</td>
                                        <td><?php echo ($data["users"]["administrativos_id"]) ? "<a href='http://localhost:8000/administrativos/show/".$data["users"]["docentes_id"]."'>Ver perfil Administrativo</a>" : "No tiene perfil Administrativo";?></td>
                                    </tr>
                                </tbody>
                                
                            </table>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>



            <br>
    </div>
        <footer class="py-4 bg-success footer fixed-bottom">  
            <div class="container-fluid">
                <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
            </div>
            <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    </body>

    </html>