<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <title>Usuarios</title>
    <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="custom.css">
    <script src="https://kit.fontawesome.com/d1fbf856e0.js" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
        <a class="navbar-brand" href="http://localhost:8000/usuarios"><i class="fas fa-arrow-left fa-2x"></i></a>
        <div class="container">

            <a class="navbar-brand" href="http://localhost:8000/">Gestión de Perfiles</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>


    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">

            <h1 class="display-3" align="center">Perfil de Usuario</h1>

        </header>

        <div class="row">
            <div class="col-12 justify-content-center d-flex">
                    <i class="fas fa-user fa-10x border m-4 p-4"></i>
                    
            </div>
            <div class="col-6">
                <div class="card table-sm">
                    <div class="card-header">
                        <h5 class="card-tittle my-2">Informacion General</h5>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <td>Nombre completo</td>
                                    <td><?php echo $data["users"]["name"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Cedula</td>
                                    <td><?php echo $data["users"]["cedula"]; ?></td>
                                </tr>
                            </tbody>
                            
                        </table>
                    </div>
                    
                </div>
            </div>
            <div class="col-6">
                <div class="col-12">
                    <div class="card table-sm">
                        <div class="card-header">
                            <h5 class="card-tittle my-2">Perfiles</h5>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tbody>
                                    <tr>
                                        <td>Nombre completo</td>
                                        <td><?php echo ($data["users"]["docentes_id"]) ? "<a href='http://localhost:8000/docentes/show/".$data["users"]["docentes_id"]."'>Ver perfil docente</a>" : "<a href='#' data-toggle='modal' data-target='#new_docente'>No tiene perfil Docente <i class='fas fa-user-plus'></i></a>";?></td>
                                    </tr>
                                    <tr>
                                        <td>Cedula</td>
                                        <td><?php echo ($data["users"]["administrativos_id"]) ? "<a href='http://localhost:8000/administrativos/show/".$data["users"]["administrativos_id"]."'>Ver perfil Administrativo</a>" : "<a href='#' data-toggle='modal' data-target='#new_administrativo'>No tiene perfil Administrativo <i class='fas fa-user-plus'></i></a>";?></td>
                                    </tr>
                                </tbody>
                                
                            </table>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>



            <br>
    </div>
        <footer class="py-4 bg-success footer fixed-bottom">  
            <div class="container-fluid">
                <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
            </div>
            <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Modal -->
    <div class="modal fade" id="new_docente" tabindex="-1" role="dialog" aria-labelledby="new_docenteLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="new_docenteLabel">Crear Perfil Docente</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="http://localhost:8000/docentes/create" method="post">
                <input type="hidden" name="id" value=<?php echo '"'.$data['users']['id'].'"';?>>
                <input type="hidden" name="nombre" value=<?php echo '"'.$data['users']['name'].'"';?>>
                <input type="hidden" name="cedula" value=<?php echo '"'.$data['users']['cedula'].'"';?>>
                <h3>Esta seguro que desea crearle a <strong><?php echo $data['users']['name'];?></strong> un perfil de Docente?</h3>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="new_administrativo" tabindex="-1" role="dialog" aria-labelledby="new_administrativoLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="new_administrativoLabel">Crear Perfil Administrativo</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="http://localhost:8000/administrativos/create" method="post">
                <input type="hidden" name="id" value=<?php echo '"'.$data['users']['id'].'"';?>>
                <input type="hidden" name="nombre" value=<?php echo '"'.$data['users']['name'].'"';?>>
                <input type="hidden" name="cedula" value=<?php echo '"'.$data['users']['cedula'].'"';?>>
                <h3>Esta seguro que desea crearle a <strong><?php echo $data['users']['name'];?></strong> un perfil de Administrativo?</h3>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    </body>

    </html>