<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <title>Usuarios</title>
    <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="custom.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Gestión de Perfiles</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>


    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">

            <h1 class="display-3" align="center">Perfil de Usuario</h1>

        </header>


        <!-- Page Features -->
        <div class="row justify-content-md-center"> 
            <form action="mailto:tu@direccion.es" method="post" enctype="text/plain">
                <center><table bgcolor="#cccccc" border="0" cellpadding="6" cellspacing="0" width="400">
                    <tr align="center">
                        <th colspan="3" style="color: Green"><h2>Informacion general del Docente</h2></th>
                    </tr>
                    <tr align="center">
                        <th ><h3>Datos</h3></th>
                        <th ><h3>Informacion Actuales</h3></th>
                    </tr>
                    <tr>
                        <td align="right" valign="top"><b>Nombre Completo</b></td>
                        <td><input type="text" name="texto" size="25" value="{echo docente['nombre']}" readonly></td>
                        
                    </tr>
                    <tr>
                        <td align="right" valign="top"><b>Cedula</b></td>
                        <td><input type="text" name="texto" size="25" value="{echo docente['cedula']}" readonly></td>
                        
                    </tr>
                        </table>
                    </center>
                </form>
            </div>
            <!-- /.row -->
            <br>
    </div>
        <footer class="py-4 bg-success footer fixed-bottom">  
            <div class="container-fluid">
                <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
            </div>
            <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    </body>

    </html>