<!-- PHP necesario para que se registre una persona, en este caso se solicita que la secretaria, ponga el nombre de usuario y clave que usara el nuevo usuario-->
<?php 
    if(isset($_POST['submit'])){
    $nombre= $_POST['nombre'];
    $pass= $_POST['password'];

    echo $nombre;
    echo $password;
    }
?>
<!DOCTYPE html>
<html lang="es">
    <head>
        <!--La "cabeza" de la pagina, es su titulo, el php incluido es para que incluya detalles del boostrap  -->
        <meta charset="UTF-8" />
        <title>Registro de Usuario</title>
        <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
    </head>
    <body>
        <!--Para un mejor control, creamos el cuerpo a base de contenedores, que a su vez se dividen en otras secciones (row y column), tambien aparece navbar y tiene la misma funcion que la antes mencionada-->
        <div class="container">
              <div class="row justify-content-center">
                        <div class="col-3" align="center">
                            <br>
                        <img src="http://www.utp.ac.pa/documentos/2015/imagen/logo_utp_1_300.jpg" style="width:150px;height:150px">
                        </div>

                            <div class="col-6" align="center">
                                <br><br>

                            <fieldset>
                            <legend><h2 style="text-align:center;color: #709e07">Universidad Tecnológica de Panamá</h2></legend>
                            <legend><h2 style="text-align:center; color: #709e07">Control de perfil de la FISC</h2></legend><br><br>
                            <legend><h2 style="text-align:center; font-family: 'Lilita One', cursive;">Registro de Usuario</h2></legend>
                            </fieldset>
                            </div>

                         <div class="col-3" align="center">
                            <br>
                        <img src="https://pbs.twimg.com/profile_images/1099046790463193093/nb9L_nav_400x400.png" style="width:150px;height:150px;" align="right">
                        </div>
                </div>

              <div class="row justify-content-center">
                    <div class="col-4" align="center">
                        <br><br>
                        <form action="http://localhost:8000/usuarios/create"  method="post">
                            <label>Nombre:</label>
                            <input type="text" name="nombre" placeholder="Ej. Juana González" class="form-control" required="true">
                            <br>
                            <label>Número de Cédula:</label>
                            <input type="text" name="cedula" placeholder="Ej. #-###-###" class="form-control"required="true">
                            <br>
                            <label>Contraseña:</label>
                            <input type="password" name="pass" placeholder="Mínimo 8 Caracteres" class="form-control" required="true">
                            <br><br>                          
                            <input type="submit" value="Validar" name="submit" class="btn btn-success" required="true">
                            <br><br>
                            <p>Ya tienes cuenta? <a href="http://localhost:8000/usuarios/login">Inicia sesion aqui</a></p>
                        </form> 
                    </div>
                </div>
        </div>
    </body>
</html>

