<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8" />
	<title>Docentes</title>
	<?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="custom.css">
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
		<div class="container">
			<a class="navbar-brand" href="#">Gestión de Perfiles</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		</div>
	</nav>


  <div class="container">

    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">

      <h1 class="display-3" align="center">Actualizacion de la Informacion</h1>

    </header>


    <!-- Page Features -->
    <div class="row justify-content-md-center"> 
      <form action="mailto:tu@direccion.es" method="post" enctype="text/plain">
        <center><table bgcolor="#cccccc" border="0" cellpadding="6"
          cellspacing="0" width="400">
          <tr align="center">
            <th colspan="3" style="color: Green"><h2>Informacion general del Docente</h2></th>
          </tr>
          <tr align="center">
            <th ><h3>Datos</h3></th>
            <th ><h3>Informacion Actuales</h3></th>
            <th ><h3>Actualizar informacion</h3></th>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Nombre Completo</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['nombre']}" readonly></td>
            <td><input type="text" size="25" name="nombre"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Cedula</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['cedula']}" readonly></td>
            <td><input type="number" size="30" name="cedula" disabled> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Fecha de Nacimiento</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['fecha_nacimiento']}" readonly></td>
            <td><input type="Date" size="30" name="fecha_nacimiento" disabled> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Genero</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['genero']}" readonly></td>
            <td><select name="genero">
              <option>Femenino</option>
              <option>Masculino</option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Estado civil</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['estado_civil']}" readonly></td>
            <td><select name="estado_civil">
              <option>Soltero</option>
              <option>Casado</option>
              <option>Viudo</option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Tipo de sangre</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['tipo_sangre']}" readonly></td>
            <td><input type="text" size="25" name="tipo_sangre"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Peso</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['peso']}" readonly></td>
            <td><input type="number" size="25" name="peso"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Estatura</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['estatura']}" readonly></td>
            <td><input type="number" size="25" name="estatura"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Direccion(provincia)</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['provincia']}" readonly></td>
            <td><select name="provincia">
              <option>Bocas del Toro</option>
              <option>Cocle</option>
              <option>Colón</option>
              <option>Chiriquí</option>
              <option>Darien</option>
              <option>Herrea</option>
              <option>Los Santos</option>
              <option>Panamá</option>
              <option>Veraguas</option>
              <option>Panamá Oeste</option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Direccion(distrito)</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['distrito']}" readonly></td>
            <td><select name="distrito">
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Direccion(corregimiento)</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['corregimiento']}" readonly></td>
            <td><select name="corregimiento">
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
              <option></option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Direccion</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['direccion']}" readonly></td>
            <td><input type="text" size="25" name="direccion"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Telefono</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['telefono']}" readonly></td>
            <td><input type="number" size="25" name="telefono"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Correro</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['correo']}" readonly></td>
            <td><input type="email" size="25" name="correo"> </td>
          </tr>

          <tr>
            <td align="right" valign="top"><b>Categoria del docente</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['categoria']}" readonly></td>
            <td><select name="categoria">
              <option>Tiempo completo</option>
              <option>MTiempo parcial</option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Ubicacion(sede)</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['sede']}" readonly></td>
            <td><select name="sede">
              <option>Azuero</option>
              <option>Bocas Del Toro</option>
              <option>Chiriqui</option>
              <option>Cocle</option>
              <option>Colon</option>
              <option>Panamá Oeste</option>
              <option>Veraguas</option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Departamento</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['departamento']}" readonly></td>
            <td><select name="departamento">
              <option>No Definido</option>
              <option>Arquitectura y Redes de Computadoras</option>
              <option>Computación y Simulación de Sistemas</option>
              <option>Ingeniería de Software</option>
              <option>Programación de Computadoras</option>
              <option>Sistemas de Información, Control y Evaluación de Recursos Informáticos</option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Cargo Administrativo</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['cargo']}" readonly></td>
            <td><select name="cargo">
              <option>Sin cargo</option>
              <option>Decano</option>
              <option>Vicedecano</option>
              <option>Jefe de Departamento</option>
              <option>Coordinador de Carrera</option>
              <option>Coordinador de FISC en Centro Regional</option>
              <option>Coordinador de Extensión</option>
              <option>Coordinador de Postgrado</option>
              <option>Coordinador de Investigación</option>
              <option>Director de Centro Regional</option>
              <option>Subdirector Académico de Centro Regional</option>
              <option>Subdirector de investigación, postgrado y extensión de Centro Regiona</option>
              <option>Subdirector Administrativo de Centro Regional</option>
              <option>Coordinador de Extensión en Centro Regional</option>
              <option>Coordinador de Postgrado en Centro Regional</option>
              <option>Coordinador de Investigación en Centro Regional</option>
            </select></td>
          </tr>
            <td align="right" valign="top"><b>Extencion</b></td>
            <td><input type="text" name="texto" size="25" value="{echo docente['extencion']}" readonly></td>
            <td><input type="text" size="25" name="extencion"> </td>
          </tr>
          <!-- /tabla 1 -->


          <tr align="center">
            <th colspan="3" style="color: Green"><h2>Informacion Familiar</h2></th>
          </tr>
          <tr align="center">
            <th ><h3>Datos</h3></th>
            <th ><h3>Informacion Actuales</h3></th>
            <th ><h3>Actualizar informacion</h3></th>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Nombre y apellido</b></td>
            <td><input type="text" name="texto" size="25" value="{echo familia_docente['IFNombre']}" readonly></td>
            <td><input type="text" size="25" name="IFNombre"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Fecha de nacimiento(requiere si es hijo)</b></td>
            <td><input type="text" name="texto" size="25" value="{echo familia_docente['fecha_nacimiento']}" readonly></td>
            <td><input type="number" size="25" name="fecha_nacimiento"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>¿Localizar en caso de emergancia?</b></td>
            <td><input type="text" name="texto" size="25" value="{echo familia_docente['localizar_emergiencia']}" readonly></td>
            <td><select name="localizar_emergiencia">
              <option>Si</option>
              <option>No</option>
            </select></td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Prioridad de localizar en caso de emergencia</b></td>
            <td><input type="text" name="texto" size="25" value="{echo familia_docente['prioridad_emergencia']}" readonly></td>
            <td><input type="number" size="25" name="prioridad_emergencia"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Telefono de oficina</b></td>
            <td><input type="text" name="texto" size="25" value="{echo familia_docente['telefono']}" readonly></td>
            <td><input type="number" size="25" name="telefono"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Correo electronico</b></td>
            <td><input type="text" name="texto" size="25" value="{echo familia_docente['correo']}" readonly></td>
            <td><input type="number" size="25" name="correo"> </td>
          </tr>
          <!-- /.tabla 2 -->
          <tr align="center">
            <th colspan="3" style="color: Green"><h2>Preparacion academica del docente</h2></th>
          </tr>
          <tr align="center">
            <th ><h3>Datos</h3></th>
            <th ><h3>Informacion Actuales</h3></th>
            <th ><h3>Actualizar informacion</h3></th>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Nombre de los titulos</b></td>
            <td><input type="text" name="texto" size="25" value="{echo preparacion_docente['nombre']}" readonly></td>
            <td><input type="text" size="25" name="nombre"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Grado</b></td>
            <td><input type="text" name="texto" size="25" value="{echo preparacion_docente['grado']}" readonly></td>
            <td><input type="text" size="25" name="grado"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Año</b></td>
            <td><input type="text" name="texto" size="25" value="{echo preparacion_docente['year']}" readonly></td>
            <td><input type="number" size="25" name="year"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Institucion</b></td>
            <td><input type="text" name="texto" size="25" value="{echo preparacion_docente['universidad']}" readonly></td>
            <td><input type="text" size="25" name="universidad"> </td>
          </tr>
          <tr>
            <td align="right" valign="top"><b>Guardar</b>&nbsp; <b>&gt;</b> </td>
            <td align="center">&nbsp; <input type="submit" name="Enviar datos" value=" Guardar "><input type="reset" value="Borrar" name="B1"> </td>
            </tr>

          </table>
        </center>
      </form>
    </div>
    <!-- /.row -->
<br>
  </div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-4 bg-success">  
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
		</div>
		<!-- /.container -->
	</footer>

	<!-- Bootstrap core JavaScript -->
	<script src="vendor/jquery/jquery.min.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>
