<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Docentes</title>
        <?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
    </head>
    <body>
    	<?php include '/var/www/app/views/layouts/nav.php'; ?>
        <footer class="py-4 bg-success footer fixed-bottom">  
            <div class="container-fluid">
                <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
            </div>
            <!-- /.container -->
        </footer>
    </body>
</html>
