<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8" />
	<title>Docentes</title>
	<?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="custom.css">
	<script src="https://kit.fontawesome.com/d1fbf856e0.js" crossorigin="anonymous"></script>
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
		<div class="container">
			<a class="navbar-brand" href="#">Gestión de Perfiles</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		</div>
	</nav>


	<div class="container">

		<!-- Jumbotron Header -->
		<header class="jumbotron my-4">

			<h1 class="display-3" align="center">Actualizacion de la Informacion</h1>

		</header>

    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">

            <h1 class="display-3" align="center">Perfil de Usuario</h1>

        </header>

        <div class="row">
            <div class="col-12 justify-content-center d-flex">
                    <i class="fas fa-user fa-10x border m-4 p-4"></i>
                    
            </div>
            <div class="col-5">
                <div class="card table-sm">
                    <div class="card-header">
                        <h5 class="card-tittle my-2">Informacion General</h5>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <td>Nombre completo</td>
                                    <td><?php echo $data["docente"]["nombre"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Cedula</td>
                                    <td><?php echo $data["docente"]["cedula"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Fecha de nacimiento</td>
                                    <td><?php echo $data["docente"]["fecha_nacimiento"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Genero</td>
                                    <td><?php echo $data["docente"]["genero"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Tipo de sangre</td>
                                    <td><?php echo $data["docente"]["tipo_sangre"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Estado civil</td>
                                    <td><?php echo $data["docente"]["estado_civil"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Peso</td>
                                    <td><?php echo $data["docente"]["peso"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Estatura</td>
                                    <td><?php echo $data["docente"]["estatura"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Provincia</td>
                                    <td><?php echo $data["docente"]["provincia"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Distrito</td>
                                    <td><?php echo $data["docente"]["distrito"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Corregimiento</td>
                                    <td><?php echo $data["docente"]["corregimiento"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Direccion</td>
                                    <td><?php echo $data["docente"]["direccion"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Telefono</td>
                                    <td><?php echo $data["docente"]["telefono"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Correo</td>
                                    <td><?php echo $data["docente"]["correo"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Sede</td>
                                    <td><?php echo $data["docente"]["sede"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Categoria</td>
                                    <td><?php echo $data["docente"]["categoria"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Departamento</td>
                                    <td><?php echo $data["docente"]["departamento"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Apartado postal</td>
                                    <td><?php echo $data["docente"]["apartado_postal"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Cargo</td>
                                    <td><?php echo $data["docente"]["cargo"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Represante de gobierno</td>
                                    <td><?php echo $data["docente"]["representante_gobierno"]; ?></td>
                                </tr>
                                <tr>
                                    <td>Unidad</td>
                                    <td><?php echo $data["docente"]["unidad"]; ?></td>
                                </tr>
                            </tbody>
                            
                        </table>
                    </div>
                    
                </div>
            </div>
            <div class="col-7">
                <div class="col-12">
                    <div class="card table-sm">
                        <div class="card-header">
                            <h5 class="card-tittle my-2">Preparacion academica</h5>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped">
                            	<thead>
                            		<th>Titulo</th>
                            		<th>Anho</th>
                            		<th>Institucion</th>
                            		<th>Grado</th>
                            	</thead>
                                <tbody>
                                    <td><?php echo ($data["users"]["docentes_id"]) ? "<a href='http://localhost:8000/docentes/show/".$data["users"]["docentes_id"]."'>Ver perfil docente</a>" : "<a href='#' data-toggle='modal' data-target='#new_docente'>No tiene perfil Docente <i class='fas fa-user-plus'></i></a>";?>
                                    </td>
                                    <td><?php echo ($data["users"]["docentes_id"]) ? "<a href='http://localhost:8000/docentes/show/".$data["users"]["docentes_id"]."'>Ver perfil docente</a>" : "<a href='#' data-toggle='modal' data-target='#new_docente'>No tiene perfil Docente <i class='fas fa-user-plus'></i></a>";?>
                                    </td>
                                    <td><?php echo ($data["users"]["docentes_id"]) ? "<a href='http://localhost:8000/docentes/show/".$data["users"]["docentes_id"]."'>Ver perfil docente</a>" : "<a href='#' data-toggle='modal' data-target='#new_docente'>No tiene perfil Docente <i class='fas fa-user-plus'></i></a>";?>
                                    </td>
                                    <td><?php echo ($data["users"]["docentes_id"]) ? "<a href='http://localhost:8000/docentes/show/".$data["users"]["docentes_id"]."'>Ver perfil docente</a>" : "<a href='#' data-toggle='modal' data-target='#new_docente'>No tiene perfil Docente <i class='fas fa-user-plus'></i></a>";?>
                                    </td>
                                </tbody>
                                
                            </table>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
		<!-- Page Features -->
		<div class="row justify-content-md-center"> 
			<form action="mailto:tu@direccion.es" method="post" enctype="text/plain">
				<center><table bgcolor="#cccccc" border="0" cellpadding="6" cellspacing="0" width="400">
					<tr align="center">
						<th colspan="3" style="color: Green"><h2>Informacion general del Docente</h2></th>
					</tr>
					<tr align="center">
						<th ><h3>Datos</h3></th>
						<th ><h3>Informacion Actuales</h3></th>
					</tr>
					<tr>
						<td align="right" valign="top"><b>Nombre Completo</b></td>
						<td><input type="text" name="texto" size="25" value="{echo docente['nombre']}" readonly></td>
						
					</tr>
					<tr>
						<td align="right" valign="top"><b>Cedula</b></td>
						<td><input type="text" name="texto" size="25" value="{echo docente['cedula']}" readonly></td>
						
					</tr>
					<tr>
						<td align="right" valign="top"><b>Fecha de Nacimiento</b></td>
						<td><input type="text" name="texto" size="25" value="{echo docente['fecha_nacimiento']}" readonly></td>
						
					</tr>
					<tr>
						<td align="right" valign="top"><b>Genero</b></td>
						<td><input type="text" name="texto" size="25" value="{echo docente['genero']}" readonly></td>

						<tr>
							<td align="right" valign="top"><b>Estado civil</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['estado_civil']}" readonly></td>
						</tr>
						<tr>
							<td align="right" valign="top"><b>Tipo de sangre</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['tipo_sangre']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Peso</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['peso']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Estatura</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['estatura']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Direccion(provincia)</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['provincia']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Direccion(distrito)</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['distrito']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Direccion(corregimiento)</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['corregimiento']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Direccion</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['direccion']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Telefono</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['telefono']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Correro personal</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['correo']}" readonly></td>

						</tr>

						<tr>
							<td align="right" valign="top"><b>Categoria del docente</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['categoria']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Ubicacion(sede)</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['sede']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Departamento</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['departamento']}" readonly></td>
						</tr>
						<tr>
							<td align="right" valign="top"><b>Cargo Administrativo</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['cargo']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Extencion</b></td>
							<td><input type="text" name="texto" size="25" value="{echo docente['extencion']}" readonly></td>
						</tr>
						<!-- /tabla 1 -->

					</tr>
					<tr align="center">
						<th ><h3>Datos</h3></th>
						<th ><h3>Informacion Actuales</h3></th>

					</tr>
					<tr align="center">
						<th colspan="3" style="color: Green"><h2>Informacion Familiar</h2></th>
					</tr>

					<tr>
						<td align="right" valign="top"><b>Nombre y apellido</b></td>
						<td><input type="text" name="texto" size="25" value="{echo familia_docente['IFNombre']}" readonly></td>

					</tr>
					<tr>
						<td align="right" valign="top"><b>Fecha de nacimiento(requiere si es hijo)</b></td>
						<td><input type="text" name="texto" size="25" value="{echo familia_docente['fecha_nacimiento']}" readonly></td>

					</tr>
					<tr>
						<td align="right" valign="top"><b>¿Localizar en caso de emergancia?</b></td>
						<td><input type="text" name="texto" size="25" value="{echo familia_docente['localizar_emergiencia']}" readonly></td>

						<tr>
							<td align="right" valign="top"><b>Prioridad de localizar en caso de emergencia</b></td>
							<td><input type="text" name="texto" size="25" value="{echo familia_docente['prioridad_emergencia']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Telefono de oficina</b></td>
							<td><input type="text" name="texto" size="25" value="{echo familia_docente['telefono']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Correo electronico</b></td>
							<td><input type="text" name="texto" size="25" value="{echo familia_docente['correo']}" readonly></td>

						</tr>
						<!-- /.tabla 2 -->
						<tr align="center">
							<th colspan="3" style="color: Green"><h2>Preparacion academica del docente</h2></th>
						</tr>
						<tr align="center">
							<th ><h3>Datos</h3></th>
							<th ><h3>Informacion Actuales</h3></th>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Nombre de los titulos</b></td>
							<td><input type="text" name="texto" size="25" value="{echo preparacion_docente['nombre']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Grado</b></td>
							<td><input type="text" name="texto" size="25" value="{echo preparacion_docente['grado']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Año</b></td>
							<td><input type="text" name="texto" size="25" value="{echo preparacion_docente['year']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Institucion</b></td>
							<td><input type="text" name="texto" size="25" value="{echo preparacion_docente['universidad']}" readonly></td>

						</tr>

						<tr>
							<td align="right" valign="top"><b>Editar Perfil</b>&nbsp; <b>&gt;</b> </td>
							<td align="center">&nbsp; <input type="submit" name="Enviar datos" value=" Editar "> </td>
							</tr>
						</table>
					</center>
				</form>
			</div>
			<!-- /.row -->
			<br>
		</div>
		<!-- /.container -->
		<!-- Footer -->
        <footer class="py-4 bg-success footer fixed-bottom">  
            <div class="container-fluid">
                <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
            </div>
            <!-- /.container -->
        </footer>

		<!-- Bootstrap core JavaScript -->
		<script src="vendor/jquery/jquery.min.js"></script>
		<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	</body>

	</html>