<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8" />
	<title>Docentes</title>
	<?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="custom.css">
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
		<div class="container">
			<a class="navbar-brand" href="#">Gestión de Perfiles</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		</div>
	</nav>


	<div class="container">

		<!-- Jumbotron Header -->
		<header class="jumbotron my-4">

			<h1 class="display-3" align="center">Perfil Administrativo</h1>

		</header>


		<!-- Page Features -->
		<div class="row justify-content-md-center"> 
			<form action="mailto:tu@direccion.es" method="post" enctype="text/plain">
				<center><table bgcolor="#cccccc" border="0" cellpadding="6" cellspacing="0" width="400">
					<tr align="center">
						<th colspan="3" style="color: Green"><h2>Informacion general del Administrativo</h2></th>
					</tr>
					<tr align="center">
						<th ><h3>Datos</h3></th>
						<th ><h3>Informacion Actuales</h3></th>
					</tr>
					<tr>
						<td align="right" valign="top"><b>Nombre Completo</b></td>
						<td><input type="text" name="texto" size="25" value="{echo administrativo['nombre']}" readonly></td>
						
					</tr>
					<tr>
						<td align="right" valign="top"><b>Cedula</b></td>
						<td><input type="text" name="texto" size="25" value="{echo administrativo['cedula']}" readonly></td>
						
					</tr>
					<tr>
						<td align="right" valign="top"><b>Fecha de Nacimiento</b></td>
						<td><input type="text" name="texto" size="25" value="{echo administrativo['fecha_nacimiento']}" readonly></td>
						
					</tr>
					<tr>
						<td align="right" valign="top"><b>Genero</b></td>
						<td><input type="text" name="texto" size="25" value="{echo administrativo['genero']}" readonly></td>

						<tr>
							<td align="right" valign="top"><b>Estado civil</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['estado_civil']}" readonly></td>
						</tr>
						<tr>
							<td align="right" valign="top"><b>Tipo de sangre</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['tipo_sangre']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Peso</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['peso']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Estatura</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['estatura']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Direccion(provincia)</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['provincia']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Direccion(distrito)</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['distrito']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Direccion(corregimiento)</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['corregimiento']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Direccion</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['direccion']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Telefono</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['telefono']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Correo</b></td>
							<td><input type="email" name="texto" size="25" value="{echo administrativo['correo']}" readonly></td>
							<tr>
								<td align="right" valign="top"><b>Ubicacion(sede)</b></td>
								<td><input type="text" name="texto" size="25" value="{echo administrativo['sede']}" readonly></td>

							</tr>
						</tr>

						<tr>
							<td align="right" valign="top"><b>Categoria del docente</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['categoria']}" readonly></td>

						</tr>
						
						<tr>
							<td align="right" valign="top"><b>Departamento</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['departamento']}" readonly></td>
						</tr>
						<tr>
							<td align="right" valign="top"><b>Cargo Administrativo</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['cargo']}" readonly></td>

						</tr>

						<tr>
							<td align="right" valign="top"><b>Representación ante órganos de gobierno </b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['representante_gobierno']}" readonly></td>
						</tr>
						<tr>
							<td align="right" valign="top"><b>Unidad</b></td>
							<td><input type="text" name="texto" size="25" value="{echo administrativo['unidad']}" readonly></td>
						</tr>
						<!-- /tabla 1 -->

					</tr>
					<tr align="center">
						<th ><h3>Datos</h3></th>
						<th ><h3>Informacion Actuales</h3></th>

					</tr>
					<tr align="center">
						<th colspan="3" style="color: Green"><h2>Informacion Familiar</h2></th>
					</tr>

					<tr>
						<td align="right" valign="top"><b>Nombre y apellido</b></td>
						<td><input type="text" name="texto" size="25" value="{echo familia_administrativo['nombre']}" readonly></td>

					</tr>
					<tr>
						<td align="right" valign="top"><b>Parentesco</b></td>
						<td><input type="text" name="texto" size="25" value="{echo familia_administrativo['parentesco']}" readonly></td>

					</tr>
					<tr>
						<td align="right" valign="top"><b>Fecha de nacimiento(requiere si es hijo)</b></td>
						<td><input type="text" name="texto" size="25" value="{echo familia_administrativo['fecha_nacimiento']}" readonly></td>

					</tr>
					<tr>
						<td align="right" valign="top"><b>¿Localizar en caso de emergancia?</b></td>
						<td><input type="text" name="texto" size="25" value="{echo familia_administrativo['localizar_emergiencia']}" readonly></td>

						<tr>
							<td align="right" valign="top"><b>Prioridad de localizar en caso de emergencia</b></td>
							<td><input type="text" name="texto" size="25" value="{echo familia_administrativo['prioridad_emergencia']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Telefono de oficina</b></td>
							<td><input type="text" name="texto" size="25" value="{echo familia_administrativo['telefono']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Correo electronico</b></td>
							<td><input type="text" name="texto" size="25" value="{echo familia_administrativo['correo']}" readonly></td>

						</tr>
						<!-- /.tabla 2 -->
						<tr align="center">
							<th colspan="3" style="color: Green"><h2>Preparacion academica del Administrativo</h2></th>
						</tr>
						<tr align="center">
							<th ><h3>Datos</h3></th>
							<th ><h3>Informacion Actuales</h3></th>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Nombre de los titulos</b></td>
							<td><input type="text" name="texto" size="25" value="{echo preparacion_administrativo['nombre']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Grado</b></td>
							<td><input type="text" name="texto" size="25" value="{echo preparacion_administrativo['grado']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Año</b></td>
							<td><input type="text" name="texto" size="25" value="{echo preparacion_administrativo['year']}" readonly></td>

						</tr>
						<tr>
							<td align="right" valign="top"><b>Institucion</b></td>
							<td><input type="text" name="texto" size="25" value="{echo preparacion_administrativo['universidad']}" readonly></td>

						</tr>

						<tr>
							<td align="right" valign="top"><b>Editar Perfil</b>&nbsp; <b>&gt;</b> </td>
							<td align="center">&nbsp; <input
								type="submit" name="Enviar datos" value=" Editar "> </td>
							</tr>
						</table>
					</center>
				</form>
			</div>
			<!-- /.row -->
			<br>
		</div>
		<!-- /.container -->

        <footer class="py-4 bg-success footer fixed-bottom">  
            <div class="container-fluid">
                <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
            </div>
            <!-- /.container -->
        </footer>

		<!-- Bootstrap core JavaScript -->
		<script src="vendor/jquery/jquery.min.js"></script>
		<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	</body>

	</html>