<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8" />
	<title>Administrativo</title>
	<?php include '/var/www/app/views/layouts/bootstrap.php'; ?>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="custom.css">
	<script src="https://kit.fontawesome.com/d1fbf856e0.js" crossorigin="anonymous"></script>
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
		<div class="container">
			<a class="navbar-brand" href="http://localhost:8000/">Gestión de Perfiles</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		</div>
	</nav>

    <div class="container">

    	<div class="content pb-5">
        	<!-- Jumbotron Header -->
	        <header class="jumbotron my-4">

	            <h1 class="display-3" align="center">Perfil de Administrativo</h1>

	        </header>

	        <div class="row">
	            <div class="col-12 justify-content-center d-flex">
	                <i class="fas fa-user fa-10x border m-4 p-4"></i>
	                    
	            </div>
	            <div class="col-5">
	                <div class="card table-sm">
	                    <div class="card-header">
	                        <h5 class="card-tittle my-2">Informacion General</h5>
	                    </div>
	                    <div class="table-responsive">
	                        <table class="table table-striped">
	                            <tbody>
	                                <tr>
	                                    <td>Nombre completo</td>
	                                    <td><?php echo $data["administrativo"]["nombre"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Cedula</td>
	                                    <td><?php echo $data["administrativo"]["cedula"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Fecha de nacimiento</td>
	                                    <td><?php echo $data["administrativo"]["fecha_nacimiento"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Genero</td>
	                                    <td><?php echo $data["administrativo"]["genero"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Tipo de sangre</td>
	                                    <td><?php echo $data["administrativo"]["tipo_sangre"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Estado civil</td>
	                                    <td><?php echo $data["administrativo"]["estado_civil"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Peso</td>
	                                    <td><?php echo $data["administrativo"]["peso"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Estatura</td>
	                                    <td><?php echo $data["administrativo"]["estatura"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Provincia</td>
	                                    <td><?php echo $data["administrativo"]["provincia"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Distrito</td>
	                                    <td><?php echo $data["administrativo"]["distrito"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Corregimiento</td>
	                                    <td><?php echo $data["administrativo"]["corregimiento"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Direccion</td>
	                                    <td><?php echo $data["administrativo"]["direccion"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Telefono</td>
	                                    <td><?php echo $data["administrativo"]["telefono"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Correo</td>
	                                    <td><?php echo $data["administrativo"]["correo"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Sede</td>
	                                    <td><?php echo $data["administrativo"]["sede"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Categoria</td>
	                                    <td><?php echo $data["administrativo"]["categoria"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Departamento</td>
	                                    <td><?php echo $data["administrativo"]["departamento"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Apartado postal</td>
	                                    <td><?php echo $data["administrativo"]["apartado_postal"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Cargo</td>
	                                    <td><?php echo $data["administrativo"]["cargo"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Represante de gobierno</td>
	                                    <td><?php echo $data["administrativo"]["representante_gobierno"]; ?></td>
	                                </tr>
	                                <tr>
	                                    <td>Unidad</td>
	                                    <td><?php echo $data["administrativo"]["unidad"]; ?></td>
	                                </tr>
	                            </tbody>
	                            
	                        </table>
	                    </div>
	                    
	                </div>
	            </div>
	            <div class="col-7">
	                <div class="col-12">
	                    <div class="card table-sm">
	                        <div class="card-header">
	                        	<div class="row">
		                        	<div class="col-8">
		                        		<h5 class="card-tittle my-2">Preparacion academica</h5>
		                        	</div>
		                        	<div class="col-4">
		                        		<a href="#" data-toggle='modal' data-target='#new_titulo'>Agregar Titulo <i class="fas fa-folder-plus"></i></a>
		                        	</div>
	                        	</div>
	                        </div>
	                        <div class="table-responsive">
	                            <table class="table table-striped">
	                            	<thead>
	                            		<th>Titulo</th>
	                            		<th>Anho</th>
	                            		<th>Institucion</th>
	                            		<th>Grado</th>
	                            	</thead>
	                                <tbody>
	                                	<?php 
	                                	if ($data['titles'] != null) {
		                                	foreach ($data['titles'] as $titulo) {
		                                		echo'
		                                		<tr>
			                                		<td>'.$titulo["nombre"].'</td>
			                                		<td>'.$titulo["year"].'</td>
			                                		<td>'.$titulo["universidad"].'</td>
			                                		<td>'.$titulo["grado"].'</td>
		                                		';
		                                	} 
	                                	}
	                                	?>
	                                </tbody>
	                                
	                            </table>
	                        	<?php  
	                        		if ($data['titles'] == null) {
	                            		echo "
	                            			<h2>No tiene Titulos Registrados</h2>
	                            		";
	                        		}
	                        	?>
	                        </div>
	                        
	                    </div>
	                </div>
	                <div class="col-12 pt-5 mt-5">
	                    <div class="card table-sm">
	                        <div class="card-header">
	                        	<div class="row">
		                        	<div class="col-8">
		                        		<h5 class="card-tittle my-2">Familiares</h5>
		                        	</div>
		                        	<div class="col-4">
		                        		<a href="#" data-toggle='modal' data-target='#new_familia'>Agregar Familiar <i class="fas fa-user-plus"></i></a>
		                        	</div>
	                        	</div>
	                        </div>
	                        <div class="table-responsive">
	                            <table class="table table-striped">
	                            	<thead>
	                            		<th>Nombre</th>
	                            		<th>Localizar emergencia</th>
	                            		<th>Prioridad al localizar</th>
	                            		<th>Parentesco</th>
	                            		<th>Fecha de Nacimiento</th>
	                            		<th>Telefono</th>
	                            		<th>correo</th>
	                            	</thead>
	                                <tbody>
	                                	<?php 
	                                	if ($data['familiares'] != null) {
		                                	foreach ($data['familiares'] as $familiar) {
		                                		echo'
		                                		<tr>
			                                		<td>'.$familiar["nombre"].'</td>
			                                		<td>'.$familiar["localizar_emergencia"].'</td>
			                                		<td>'.$familiar["prioridad_localizar"].'</td>
			                                		<td>'.$familiar["parentesco"].'</td>
			                                		<td>'.$familiar["fecha_nacimiento"].'</td>
			                                		<td>'.$familiar["telefono"].'</td>
			                                		<td>'.$familiar["correo"].'</td>
		                                		';
		                                	} 
	                                	}
	                                	?>
	                                </tbody>
	                            </table>
	                        	<?php  
	                        		if ($data['familiares'] == null) {
	                            		echo "
	                            			<h2>No tiene Familiares Registrados</h2>
	                            		";
	                        		}
	                        	?>
	                        </div>
	                        
	                    </div>
	                </div>

	            </div>
            </div>
        </div>
		<!-- Page Features -->
	</div>
	<!-- /.container -->

    <footer class="py-4 bg-success footer fixed-bottom">  
        <div class="container-fluid">
            <p class="m-0 text-center text-white">Copyright &copy; Universidad Tecnológica de Panamá</p>
        </div>
        <!-- /.container -->
    </footer>

	<!-- Bootstrap core JavaScript -->
	<script src="vendor/jquery/jquery.min.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


    <div class="modal fade" id="new_titulo" tabindex="-1" role="dialog" aria-labelledby="new_tituloLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="new_tituloLabel">Agregar Titulo</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="http://localhost:8000/administrativos/add_titulo" method="post">
            	<label>Titulo</label>
                <input type="text" name="titulo" class="form-control">

                <label>Anho</label>
                <input type="text" name="year" class="form-control">

                <label>Institucion</label>
                <input type="text" name="universidad" class="form-control">

                <label>Grado</label>
                <input type="text" name="grado" class="form-control">

                <input type="hidden" name="administrativos_id" value=<?php echo '"'.$data['administrativo']['id'].'"';?>>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="new_familia" tabindex="-1" role="dialog" aria-labelledby="new_familiaLabel" aria-hidden="true">
	    <div class="modal-dialog" role="document">
	        <div class="modal-content">
	          <div class="modal-header">
	            <h5 class="modal-title" id="new_familiaLabel">Agregar Familiar</h5>
	            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	              <span aria-hidden="true">&times;</span>
	            </button>
	          </div>
	          <div class="modal-body">
	            <form action="http://localhost:8000/administrativos/add_familiar" method="post">
	            	<label>Nombre</label>
	                <input type="text" name="nombre" class="form-control" required="true">

	                <label>Localizar emergencia</label>
	                <input type="text" name="localizar_emergiencia" class="form-control" required="true">

	                <label>Prioridad al localizar</label>
	                <input type="number" name="prioridad_localizar" class="form-control" required="true">

	                <label>Parentesco</label>
	                <input type="text" name="parentesco" class="form-control" required="true">

	                <label>Fecha de Nacimiento</label>
	                <input type="text" name="fecha_nacimiento" class="form-control" required="true">

	                <label>Telefono</label>
	                <input type="text" name="telefono" class="form-control" required="true">

	                <label>correo</label>
	                <input type="text" name="correo" class="form-control" required="true">

	                <input type="hidden" name="administrativo_id" required="true" value=<?php echo '"'.$data['administrativo']['id'].'"';?> >

	                <div class="modal-footer">
	                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	                    <button type="submit" class="btn btn-primary">Crear</button>
	                </div>
	            </form>
	          </div>
	        </div>
		</div>
    </div>
</body>

</html>